Repository sogrim/technion-sogrim, pull requests merged in 2023-01, with the labels that each got.

#176 Fix reverse credit parser bug
  packages/docs/pdf_ctrl_c_ctrl_v_6.txt
  packages/server/Cargo.lock
  packages/server/Cargo.toml
  packages/server/src/core/bank_rule/elective.rs
  packages/server/src/core/parser.rs
  packages/server/src/core/tests.rs
  packages/sogrim-app/package.json
  packages/sogrim-app/src/components/Footer/changes.ts
Labels: :bulb: bug, :file_folder: core, :alarm_clock: priority:critical, release:patch

#173 Handle specialization groups in bank requirement rows
  packages/server/Cargo.lock
  packages/server/Cargo.toml
  packages/server/src/api/students.rs
  packages/server/src/core/bank_rule/accumulate.rs
  packages/server/src/core/bank_rule/all.rs
  packages/server/src/core/bank_rule/mod.rs
  packages/server/src/core/degree_status/compute_bank.rs
  packages/server/src/core/degree_status/compute_status.rs
  packages/server/src/core/degree_status/mod.rs
  packages/server/src/core/degree_status/overflow.rs
  packages/server/src/core/types.rs
  packages/sogrim-app/src/components/Pages/RequirementPage/BankRequirementsTable/BankRequirementsRow.tsx
  packages/sogrim-app/src/types/data-types.ts
Labels: :file_folder: client, :file_folder: core, :bulb: refactor, :bulb: UX

#175 Refactor bank rules
  packages/server/src/core/bank_rule/chain.rs
  packages/server/src/core/bank_rule/elective.rs
  packages/server/src/core/bank_rule/iterate_courses.rs
  packages/server/src/core/bank_rule/malag.rs
  packages/server/src/core/bank_rule/mod.rs
  packages/server/src/core/bank_rule/sport.rs
  packages/server/src/core/degree_status/compute_bank.rs
  packages/server/src/core/degree_status/compute_status.rs
  packages/server/src/core/mod.rs
  packages/server/src/core/tests.rs
  packages/server/src/resources/course.rs
Labels: :file_folder: core, :bulb: refactor

#178 Introduce `Semester0Page` to allow editting semester0 courses
  packages/sogrim-app/src/components/AppPages/PagesTabs.tsx
  packages/sogrim-app/src/components/Banner/BannerDialogs/SelectCatalog.tsx
  packages/sogrim-app/src/components/Footer/Footer.tsx
  packages/sogrim-app/src/components/Pages/RequirementPage/BankRequirementsTable/BankRequirementCourseRow.tsx
  packages/sogrim-app/src/components/Pages/Semester0Page/Semester0Page.tsx
  packages/sogrim-app/src/components/Pages/SemestersPage/SemesterGrid/AddNewRow.tsx
  packages/sogrim-app/src/components/Pages/SemestersPage/SemesterGrid/EditGradeCell.tsx
  packages/sogrim-app/src/components/Pages/SemestersPage/SemesterGrid/SemesterGrid.tsx
  packages/sogrim-app/src/components/Pages/SemestersPage/SemesterGrid/semester-grid-interface.tsx
  packages/sogrim-app/src/components/Pages/SemestersPage/SemesterTabsConsts.ts
  packages/sogrim-app/src/stores/DataStore.ts
  packages/sogrim-app/src/types/data-types.ts
Labels: :file_folder: client, :bulb: feature

#180 Fix ug data upload white screen bug
  packages/server/Cargo.lock
  packages/server/Cargo.toml
  packages/sogrim-app/package.json
  packages/sogrim-app/src/components/Footer/changes.ts
  packages/sogrim-app/src/hooks/apiHooks/useUpdateUgData.tsx
Labels: :bulb: bug, :file_folder: client, :alarm_clock: priority:critical, release:patch

#181 Improve course searching experience
  packages/sogrim-app/src/components/Banner/BannerDialogs/SelectCatalog.tsx
  packages/sogrim-app/src/components/Pages/SemestersPage/SemesterGrid/AddNewRow.tsx
  packages/sogrim-app/src/components/Pages/SemestersPage/SemesterGrid/CourseAutocomplete.tsx
  packages/sogrim-app/src/hooks/apiHooks/useCoursesByFilter.tsx
Labels: :file_folder: client, :bulb: enhancement, :bulb: UX

#183 Add english requirement
  packages/server/src/api/students.rs
  packages/server/src/core/bank_rule/all.rs
  packages/server/src/core/bank_rule/malag.rs
  packages/server/src/core/bank_rule/sport.rs
  packages/server/src/core/bank_rule/tests.rs
  packages/server/src/core/degree_status/compute_bank.rs
  packages/server/src/core/degree_status/mod.rs
  packages/server/src/core/degree_status/postprocessing.rs
  packages/server/src/core/messages.rs
  packages/server/src/core/parser.rs
  packages/server/src/core/tests.rs
  packages/server/src/resources/course.rs
Labels: :alarm_clock: priority:medium, :file_folder: core, :bulb: enhancement

#186 Skip serializing course tags if `None`
  packages/server/src/core/tests.rs
  packages/server/src/resources/course.rs
Labels: :bulb: fix

#187 Fix course tags update bug
  packages/server/src/api/students.rs
  packages/server/src/db/services.rs
  packages/server/src/db/tests.rs
Labels: :bulb: bug, :file_folder: core
